shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 4
  - npm install --production
  - npm install broccoli broccoli-funnel rimraf tape
build: off
test_script: node test\test.js
cache: node_modules -> package.json
